### ISSUE TITLE
GKE Deployment Question

### ISSUE THREAD

**Issue by Red-Five** [forseti-security/config-validator#28]
Is config validator part of the forseti server process or a separate process?

If a seperate process it may make sense to deploy it in its own pod with a cluster IP service in front of it; a rule of thumb is to run only one process in a container.

**Comment by morgante** [comment]
When running in Forseti, I believe it is run as a separate process which Forseti communicates with via RPC. I agree this should likely be run inside a separate container.

**Comment by t12g** [comment]
Separate container yes, but it should be in the same pod as the caller. Currently it cannot handle multiple callers.

**Comment by Red-Five** [comment]
For now, attempting to run both in same container.

I copied over polices to GCS as per
https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#copy-over-policy-library-repository

However config validator not starting.
2019-04-29 22:24:47,947 ERROR google.cloud.forseti.scanner.scanner(run): Error running scanner: ConfigValidatorScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 117, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.0-py2.7.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 186, in run
    all_violations = self._retrieve_flattened_violations()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.0-py2.7.egg/google/cloud/forseti/scanner/scanners/config_validator_scanner.py", line 158, in _retrieve_flattened_violations
    self.validator_client.reset()
  File "build/bdist.linux-x86_64/egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "build/bdist.linux-x86_64/egg/retrying.py", line 212, in call
    raise attempt.get()
  File "build/bdist.linux-x86_64/egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "build/bdist.linux-x86_64/egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.14.0-py2.7.egg/google/cloud/forseti/scanner/scanners/config_validator_util/validator_client.py", line 129, in reset
    e.message)
ConfigValidatorServerUnavailableError



I'm not sure its picking up its policies

2019-04-29 22:24:45,492 INFO google.cloud.forseti.scanner.scanner_builder(_instantiate_scanner): {'class_name': 'ConfigValidatorScanner', 'module_name': 'config_validator_scanner', 'rule_filename': ''}

How does the validator know where to look for the polices? Do I need to specify an additional variable in forseti config server?

**Comment by morgante** [comment]
@joecheuk Can you help here?

**Comment by joecheuk** [comment]
Hi @Red-Five ,

Forseti register config validator as a systemctl service and it will require all the parameters to be in place to have the service up and running:
https://github.com/forseti-security/forseti-security/blob/69cdbe2332122eb266405f3d7834be2720fca07d/install/gcp/scripts/initialize_forseti_services.sh#L43

So in this case, assuming you have the policy-library folder in place and configure the parameter for config validator properly, you can run command `sudo systemctl start config-validator` to start the config validator service.

**Comment by Red-Five** [comment]
@joecheuk Thanks. 

Do we have a dockerfile for config-validator?
If not can you give me some pointers as to which dir(s) or file(s) and from which repo I need to pull into the image?

**Comment by joecheuk** [comment]
We don't have a dockerfile to for config validator at this moment, we only have a dockerfile to compile the .proto file.

This is the location of the config-validator implementation:
https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/validator.go

You can build the code in go by running a go command that looks like `go build -o ....`

The resulting file should look something like this:
https://github.com/forseti-security/forseti-security/tree/dev/external-dependencies/config-validator

And you can run the compiled binary with arguments same as here:
https://github.com/forseti-security/forseti-security/blob/69cdbe2332122eb266405f3d7834be2720fca07d/install/gcp/scripts/initialize_forseti_services.sh#L43

**Comment by Red-Five** [comment]
Closing this issue as Config Validator now supported on GKE.
